commented out the property <use-java-context>false</use-java-context> as a solution to a AHP 3 error on DEV.
Error:   "Some or all required database properties are not set"
[sshexec] BUILD FAILED
[sshexec] /app/home/jboss45a/deploy/build.xml:1018: The following error occurred while executing this line:
[sshexec] /app/home/jboss45a/deploy/bda-utils/bda-build-utils-1.2.8.xml:1818: Some or all required database properties are not set and /usr/local/jboss405/server/ncicb-app/server/default/deploy/oracle-ds.xml is not found. Ensure arguments passed to this macro are correct or set required database properties in your property file.
  [sshexec]
  [sshexec] Total time: 2 seconds
  [sshexec]

SVN-Revision: 4802