upgraded from ehcache-1.2.2 to the 1.7 version.  Requires ehcache-core-1.7.0.jar, ehcache-terracotta-1.7.0.jar, jsr107cache-1.0.jar, and backport-util-concurrent.jar to be in classpath and for the ehcache.xml to be under WEB-INF/classes to run without errors when using temp folders restricted by app support (usually java.io.tmp defined on the server)
ehcache error found:
009-12-08 16:25:25,140 ERROR [net.sf.ehcache.store.DiskStore] gov.nih.nci.camod.domain.ExpressionFeatureCache: Could not create disk store. Initial cause was /tmp/tmp/gov.nih.nci.camod.domain.ExpressionFeature.data (Permission denied)
java.io.FileNotFoundException: /tmp/tmp/gov.nih.nci.camod.domain.ExpressionFeature.data (Permission denied)
        at java.io.RandomAccessFile.open(Native Method)

SVN-Revision: 4989