changed  jboss.jndi.server.port to jboss.server.port in install:jboss:stop target.
Error:  Failed to shutdown jboss server at cbiovdev5058.nci.nih.gov:11199 
The JNDI port is being used even though we use the server.port with shell applications.

  [sshexec] [exec] Shutdown message has been posted to the server.
  [sshexec] [exec] Server shutdown may take a while - check logfiles for completion
  [sshexec] [exec] Please wait for the shutdown process to complete. It takes about 2-4 minutes approx.
  [sshexec] [exec] Please verify the below log for details - /usr/local/jboss-4.0.5.GA/server/ncicb-app/log/server.log
  [sshexec] [echo] Shutting down jboss with no user/password.
  [sshexec] [java] Shutdown message has been posted to the server.
  [sshexec]
  [sshexec] [java] Server shutdown may take a while - check logfiles for completion
  [sshexec]
  [sshexec] [echo] Shutting down jboss with default user/password.
  [sshexec] [java] Shutdown message has been posted to the server.
  [sshexec]
  [sshexec] [java] Server shutdown may take a while - check logfiles for completion
  [sshexec]
  [sshexec]
  [sshexec] BUILD FAILED
  [sshexec] /app/home/jboss45a/deploy/build.xml:529: The following error occurred while executing this line:
  [sshexec] /app/home/jboss45a/deploy/bda-utils/bda-build-utils-1.2.12.xml:363: Failed to shutdown jboss server at cbiovdev5058.nci.nih.gov:11199
  [sshexec]
  [sshexec] Total time: 23 seconds
 
 BUILD FAILED
 /usr/local/anthill3/agent/var/jobs/projects/caMOD/deploy_dev/camod/build/build.xml:576: The following error occurred while executing this line:
 /usr/local/anthill3/agent/var/jobs/projects/caMOD/deploy_dev/camod/target/bda-utils/bda-build-utils-1.2.12.xml:264: Remote command failed with exit status 1
 
 Total time: 1 minute 7 seconds
 command exit code: 1 

SVN-Revision: 4805